default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y jq
    - GROUP_ID=$(curl --header "PRIVATE-TOKEN:$NUGET_AUTH_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID" | jq -r .namespace.id)
    - echo "Setting up NuGet authentication..."
    - mkdir -p ~/.nuget/NuGet
    - echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
      <configuration>
        <packageSources>
          <add key=\"nuget.org\" value=\"https://api.nuget.org/v3/index.json\" />
          <add key=\"GroupPackageBeanieUtilities\" value=\"${CI_API_V4_URL}/groups/$GROUP_ID/-/packages/nuget/index.json\" />
        </packageSources>
        <packageSourceCredentials>
          <GroupPackageBeanieUtilities>
            <add key=\"Username\" value=\"$GITLAB_USER_LOGIN\" />
            <add key=\"ClearTextPassword\" value=\"$NUGET_AUTH_TOKEN\" />
          </GroupPackageBeanieUtilities>
        </packageSourceCredentials>
      </configuration>" > ~/.nuget/NuGet/NuGet.Config
  script:
    - dotnet build -c Release
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlab
  rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production