<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BeaniesUtilities.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <VersionPrefix>1.0.0</VersionPrefix>
<!--    <VersionSuffix>alpha-1.3.0</VersionSuffix>-->
    <PackageIcon>1738852015508output.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Gay.TCazier.pkg.BeaniesUtilities.Models" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="1738852015508output.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup>
    <UseMauiEssentials>false</UseMauiEssentials>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <PackageId>Gay.TCazier.pkg.BeaniesUtilities.$(AssemblyName)</PackageId>
    <Title>Base Model SQL Data Operations and Utilities</Title>
    <PackageProjectUrl>tcazier.gay</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>
</Project>